### ISSUE TITLE
GET /visits has no test coverage

### ISSUE THREAD

**Issue by billglover** [billglover/travel-log#11]
We have tests for the `/users` and `/countries` endpoints but we don't currently have tests for the `/visits` endpoint. We should add tests to confirm that `GET /visits` returns the expected objects. Once these tests pass, they will allow us to continue to work on the `/visits` endpoint whilst confirming that existing functionality still works.

**We expect:**
* The status code to equal 200
* The length of the body to be greater than zero

**We expect each item in the array:**
* To have an `id` property that is not `null`
* To have an `user_id` property that is not `null`
* To have an `user_id` property that is not `null`

**Tips:**
1. Create a new file for these tests: `./routes/visits.test.js`
1. The tests will look similar to the [tests for users](https://github.com/billglover/travel-log/blob/3057733b3950b54c44d4e2094c7d482958ffc7fa/routes/users.test.js#L20-L34)
2. The tests will require data in the `visits` table. Create a `./seeds/create-test-visits.js` file and use [this example](https://github.com/billglover/travel-log/blob/3057733b3950b54c44d4e2094c7d482958ffc7fa/seeds/create-test-users.js#L1-L12) to create some sample visits. We have not looked at this before.

**Comment by berryjen** [comment]
i will work on fixing this issue

**Comment by billglover** [comment]
Thanks @berryjen. I've allocated this issue to you.

**Comment by berryjen** [comment]
issue #11 has now been fixed :)

**Comment by billglover** [comment]
This is fixed in #14. Thanks @berryjen for the contribution.
