### ISSUE TITLE
GET /visits/:id needs implementation

### ISSUE THREAD

**Issue by billglover** [billglover/travel-log#12]
In our visits model, controller and router we have implemented the functionality for `GET /visits` which returns all visits in the database. We need to be able to retrieve details about a single visit. For example:

Request: `GET /visits/1`

**Should:**
* Return all details for visit with `id=1`
* Use a standard date format; suggested RFC3339

**Example:**

```json
{
  "id": 1,
  "country_id": 1,
  "user_id": 2,
  "arrival_time": "2006-01-02T15:04:05Z07:00",
  "departure_time": "2006-01-21T22:04:05Z07:00"
}
```

**Tips:**
1. This will require changes to the model, controller, and routes for visits.
2. There is an example of how this could work in both users and countries.
3. No database changes should be needed.

**Comment by jankvc** [comment]
Can i do this ? you can assign me

**Comment by billglover** [comment]
@jankvc Thank you for your offer of help. This issue has been earmarked for an upcoming pair programming session. Apologies this issue wasn't marked as allocated. I was planning on working through how to identify and select this issues during the coding session. In the meantime I've allocated it to myself to indicate that it has been allocated.

**Comment by berryjen** [comment]
i will attempt to debug this issue now, issue  #12

**Comment by billglover** [comment]
Thanks @berryjen. I've assigned the issue to you.
