### ISSUE TITLE
POST /visits needs implementation

### ISSUE THREAD

**Issue by billglover** [billglover/travel-log#13]
We have the ability to retrieve an array of visits but we don't currently have a way for users to create new visits. We need to allow users to submit a `POST` request to `visits` in order to create an entry in the visits table.

**Should:**

* Accept a `POST` request and respond with status `201 Created`
* Return all details for the visit created (including its `id`)
* Not allow users to include the `id` when submitting a visit
* Use a standard date format; suggested RFC3339 (see example below)
* Return an error if the user does not provide `user_id` and `country_id`

**Example:** this is an acceptable visit 👍 

```json
{
  "country_id": 1,
  "user_id": 2,
  "arrival_time": "2006-01-02T15:04:05Z07:00",
  "departure_time": "2006-01-21T22:04:05Z07:00"
}
```

**Example:** this should result in an error 👎 

```json
{
  "id": 1,
  "user_id": 2,
  "arrival_time": "2006-01-02T15:04:05Z07:00",
  "departure_time": "now"
}
```

This should result in an error because:
1. the request includes an `id`
2. The request does not include a `country_id`
3. the time is not formatted correctly, e.g. `"now"`

**Tips:**

* This will require changes to the model, controller, and routes for visits.
* There is an example of how this could work in both users and countries.
* No database changes should be needed.

**Comment by berryjen** [comment]
I will attempt to resolve this....to the best of my ability

**Comment by billglover** [comment]
Awesome! Thanks. I've assigned you the issue.
