### ISSUE TITLE
Unnecessary console.log statements in models/visits

### ISSUE THREAD

**Issue by billglover** [billglover/travel-log#16]
These `console.log` statements were included when debugging date formats. They are no longer required and could be removed.

https://github.com/billglover/travel-log/blob/5c17a1887077d0e8eaa8f9134e5ab3fd6c81adfa/models/visits.js#L22-L23

**Comment by billglover** [comment]
@berryjen this is a nice small issue if you wanted to work on something quick.

**Comment by surajrane42** [comment]
@billglover I would like to fix this. Can you please assign it to me

**Comment by berryjen** [comment]
I will get on this tonight!
